name: anonymous_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.2
  firebase_core: ^2.30.1
  http: ^1.2.0
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  flutter_secure_storage: ^9.0.0
  get_it: ^7.7.0
  email_validator: ^2.1.17
  web_socket_channel: ^2.4.5
  uuid: ^4.4.0
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/