name: api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  broadcast_bloc: ^0.1.0-dev.2
  crypto: ^3.0.3
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0
  dart_frog_web_socket: ^1.0.0
  dart_jsonwebtoken: ^2.14.0
  firedart: ^0.9.8
  username_gen: ^1.0.4
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.9
  mocktail: ^1.0.0
  test: ^1.19.2
